### ISSUE TITLE
Map saving

### ISSUE THREAD

**Issue by BikashPandey17** [Jimut123/wisp#1]
why is the map saved in the location `C:\\Users\\admin\\AppData\\Local\\Temp\\tmp20ubm6zg` which gives a `PermissionError: [Errno 13] Permission denied:` it can either save it in a chosen location or in the same directory.

Entire error message :
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\Lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "E:\git\wisp\venv\lib\site-packages\wisp-0.0.8b0-py3.7.egg\wisp.py", line 753, in show_map
    MAP_FINAL.save(tmp.name)
  File "E:\git\wisp\venv\lib\site-packages\branca\element.py", line 164, in save
    fid = open(outfile, 'wb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\admin\\AppData\\Local\\Temp\\tmpod9udnn7'`

What is the policy for contributing?

**Comment by Jimut123** [comment]
Looks like the version **0.0.8-b** of the GUI app doesn't work well in windows. Try running

`$ python wisp_v2.py` 

Which contains the actual Naive algorithm for the app (version-2). Please provide the API key beforehand... Though it only supports CLI.

If you want to make the previous release  work in windows, then I will be more than happy if you could fork it and submit a P.R.

**Comment by Jimut123** [comment]
Minor issue, closing this ..
